version: '3.8'

services:
  cache-node-1:
    build:
      context: ./cache-py # Path ke folder Dockerfile cache
      dockerfile: Dockerfile
    command: > # Perintah untuk node A
      python main.py
        --id="nodeA"
        --addr="0.0.0.0:8000" # Listen di semua interface container
        --peers="http://cache-node-2:8001,http://cache-node-3:8002" # Peers adalah node LAIN
        --capacity=10 # Contoh kapasitas
    ports:
      - "8000:8000"
    networks:
      - cache_net

  cache-node-2:
    build:
      context: ./cache-py
      dockerfile: Dockerfile
    command: > # Perintah untuk node B
      python main.py
        --id="nodeB"
        --addr="0.0.0.0:8001"
        --peers="http://cache-node-1:8000,http://cache-node-3:8002"
        --capacity=10
    ports:
      - "8001:8001"
    networks:
      - cache_net

  cache-node-3:
    build:
      context: ./cache-py
      dockerfile: Dockerfile
    command: > # Perintah untuk node C
      python main.py
        --id="nodeC"
        --addr="0.0.0.0:8002"
        --peers="http://cache-node-1:8000,http://cache-node-2:8001"
        --capacity=10
    ports:
      - "8002:8002"
    networks:
      - cache_net

networks:
  cache_net:
    driver: bridge